In [1]:
import numpy as np
import pandas as pd
from yaml import safe_load
import os
from tqdm import tqdm 
import json

In [2]:
filenames = []
for file in os.listdir('/Users/mihir/Desktop/Projects/t20 wc score predictor/dataset/t20s'):
    filenames.append(os.path.join('/Users/mihir/Desktop/Projects/t20 wc score predictor/dataset/t20s',file))

In [3]:
filenames[0:5]

['/Users/mihir/Desktop/Projects/t20 wc score predictor/dataset/t20s/1359789.yaml',
 '/Users/mihir/Desktop/Projects/t20 wc score predictor/dataset/t20s/1173055.yaml',
 '/Users/mihir/Desktop/Projects/t20 wc score predictor/dataset/t20s/951375.yaml',
 '/Users/mihir/Desktop/Projects/t20 wc score predictor/dataset/t20s/1394759.yaml',
 '/Users/mihir/Desktop/Projects/t20 wc score predictor/dataset/t20s/1400974.yaml']

In [6]:
final_df = pd.DataFrame()
counter = 1
for file in tqdm(filenames):
    with open(file, 'r') as f:
        df = pd.json_normalize(safe_load(f))
        df['match_id'] = counter
        final_df = pd.concat([final_df, df], ignore_index=True)
        counter += 1

 75%|█████████████████████████████▎         | 2689/3581 [21:30<07:08,  2.08it/s]

NotImplementedError:

In [7]:
final_df

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.city,info.dates,info.gender,info.match_type,info.match_type_number,...,info.registry.people.Masood Jayezeh,info.registry.people.Mehran Siasar,info.registry.people.Nader Zahadiafzal,info.registry.people.Naiem Bameri,info.registry.people.Navid Abdollahpour,info.registry.people.Navid Balouch,info.registry.people.Yousef Shadzehisarjou,info.registry.people.B Biza,info.registry.people.JR Loughran,info.registry.people.Mubasir Khan
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",0.92,2023-03-01,1,6.0,Buenos Aires,[2023-02-28],male,T20,2009.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'West Indies', 'deli...",0.91,2020-03-01,1,6.0,Canberra,[2020-02-26],female,T20,853.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'India', 'deliveries...",0.91,2016-03-17,2,6.0,Bangalore,[2016-03-15],female,T20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Malaysia', 'deliver...",0.92,2023-09-01,1,6.0,Bangi,[2023-09-01],female,T20,1573.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",0.92,2023-10-10,1,6.0,Lagos,[2023-10-05],male,T20,2292.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.91,2012-04-16,2,6.0,Auckland,[2012-02-11],male,T20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",0.91,2017-04-02,1,6.0,Trinidad,[2017-04-01],male,T20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",0.92,2023-10-07,2,6.0,Hangzhou,[2023-10-07],male,T20,2300.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7264b765
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",0.91,2016-03-08,1,6.0,Nagpur,[2016-03-08],male,T20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",0.91,2009-11-13,3,6.0,NaN,[2009-11-12],male,T20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
threshold = 0.5
final_df = final_df.loc[:, final_df.isnull().mean() < threshold]

final_df

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.city,info.dates,info.gender,info.match_type,info.match_type_number,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",0.92,2023-03-01,1,6.0,Buenos Aires,[2023-02-28],male,T20,2009.0,Bermuda,20,[KS Leverock],"[Bermuda, Panama]",Bermuda,bat,"[N Duguid, Vijaya Mallela]","Belgrano Athletic Club Ground, Buenos Aires",1
1,"[{'1st innings': {'team': 'West Indies', 'deli...",0.91,2020-03-01,1,6.0,Canberra,[2020-02-26],female,T20,853.0,Pakistan,20,[Javeria Khan],"[Pakistan, West Indies]",West Indies,bat,"[CA Polosak, S George]",Manuka Oval,2
2,"[{'1st innings': {'team': 'India', 'deliveries...",0.91,2016-03-17,2,6.0,Bangalore,[2016-03-15],female,T20,NaN,India,20,[H Kaur],"[India, Bangladesh]",Bangladesh,field,"[Aleem Dar, REJ Martinesz]",M Chinnaswamy Stadium,3
3,"[{'1st innings': {'team': 'Malaysia', 'deliver...",0.92,2023-09-01,1,6.0,Bangi,[2023-09-01],female,T20,1573.0,United Arab Emirates,20,"[KKN Egodage, KKN Egodage]","[Malaysia, United Arab Emirates]",Malaysia,bat,"[N Perera, Sarika Prasad]","UKM-YSD Cricket Oval, Bangi",4
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",0.92,2023-10-10,1,6.0,Lagos,[2023-10-05],male,T20,2292.0,Nigeria,20,[Sulaimon Runsewe],"[Nigeria, Sierra Leone]",Sierra Leone,field,"[M Bodie, T Oladunjoye]","Tafawa Balewa Square Cricket Oval, Lagos",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.91,2012-04-16,2,6.0,Auckland,[2012-02-11],male,T20,NaN,New Zealand,20,[MJ Guptill],"[New Zealand, Zimbabwe]",Zimbabwe,bat,"[GAV Baxter, BG Frost]",Eden Park,2685
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",0.91,2017-04-02,1,6.0,Trinidad,[2017-04-01],male,T20,NaN,West Indies,20,[E Lewis],"[West Indies, Pakistan]",Pakistan,bat,"[GO Brathwaite, LS Reifer]","Queen's Park Oval, Port of Spain",2686
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",0.92,2023-10-07,2,6.0,Hangzhou,[2023-10-07],male,T20,2300.0,Bangladesh,20,NaN,"[Pakistan, Bangladesh]",Bangladesh,field,"[Mahmood Kharoti, Sarika Prasad]",Zhejiang University of Technology Cricket Field,2687
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",0.91,2016-03-08,1,6.0,Nagpur,[2016-03-08],male,T20,NaN,Afghanistan,20,[Mohammad Shahzad],"[Afghanistan, Scotland]",Afghanistan,bat,"[M Erasmus, RK Illingworth]","Vidarbha Cricket Association Stadium, Jamtha",2688
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",0.91,2009-11-13,3,6.0,NaN,[2009-11-12],male,T20,NaN,Pakistan,20,[Imran Nazir],"[New Zealand, Pakistan]",New Zealand,field,"[Nadeem Ghauri, Zameer Haider]",Dubai International Cricket Stadium,2689

In [9]:
final_df.columns

Index(['innings', 'meta.data_version', 'meta.created', 'meta.revision',
       'info.balls_per_over', 'info.city', 'info.dates', 'info.gender',
       'info.match_type', 'info.match_type_number', 'info.outcome.winner',
       'info.overs', 'info.player_of_match', 'info.teams', 'info.toss.winner',
       'info.toss.decision', 'info.umpires', 'info.venue', 'match_id'],
      dtype='object')

In [10]:
backup = final_df.copy()

In [13]:
final_df.drop(columns = [
    'meta.data_version',
    'meta.created',
    'info.balls_per_over'   ], inplace = True)

/var/folders/qg/km03k0gn1yn690bk_brhvb3c0000gn/T/ipykernel_38011/3234434094.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(columns = [

In [14]:
final_df

,innings,meta.revision,info.city,info.dates,info.gender,info.match_type,info.match_type_number,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",1,Buenos Aires,[2023-02-28],male,T20,2009.0,Bermuda,20,[KS Leverock],"[Bermuda, Panama]",Bermuda,bat,"[N Duguid, Vijaya Mallela]","Belgrano Athletic Club Ground, Buenos Aires",1
1,"[{'1st innings': {'team': 'West Indies', 'deli...",1,Canberra,[2020-02-26],female,T20,853.0,Pakistan,20,[Javeria Khan],"[Pakistan, West Indies]",West Indies,bat,"[CA Polosak, S George]",Manuka Oval,2
2,"[{'1st innings': {'team': 'India', 'deliveries...",2,Bangalore,[2016-03-15],female,T20,NaN,India,20,[H Kaur],"[India, Bangladesh]",Bangladesh,field,"[Aleem Dar, REJ Martinesz]",M Chinnaswamy Stadium,3
3,"[{'1st innings': {'team': 'Malaysia', 'deliver...",1,Bangi,[2023-09-01],female,T20,1573.0,United Arab Emirates,20,"[KKN Egodage, KKN Egodage]","[Malaysia, United Arab Emirates]",Malaysia,bat,"[N Perera, Sarika Prasad]","UKM-YSD Cricket Oval, Bangi",4
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",1,Lagos,[2023-10-05],male,T20,2292.0,Nigeria,20,[Sulaimon Runsewe],"[Nigeria, Sierra Leone]",Sierra Leone,field,"[M Bodie, T Oladunjoye]","Tafawa Balewa Square Cricket Oval, Lagos",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",2,Auckland,[2012-02-11],male,T20,NaN,New Zealand,20,[MJ Guptill],"[New Zealand, Zimbabwe]",Zimbabwe,bat,"[GAV Baxter, BG Frost]",Eden Park,2685
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",1,Trinidad,[2017-04-01],male,T20,NaN,West Indies,20,[E Lewis],"[West Indies, Pakistan]",Pakistan,bat,"[GO Brathwaite, LS Reifer]","Queen's Park Oval, Port of Spain",2686
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",2,Hangzhou,[2023-10-07],male,T20,2300.0,Bangladesh,20,NaN,"[Pakistan, Bangladesh]",Bangladesh,field,"[Mahmood Kharoti, Sarika Prasad]",Zhejiang University of Technology Cricket Field,2687
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",1,Nagpur,[2016-03-08],male,T20,NaN,Afghanistan,20,[Mohammad Shahzad],"[Afghanistan, Scotland]",Afghanistan,bat,"[M Erasmus, RK Illingworth]","Vidarbha Cricket Association Stadium, Jamtha",2688
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",3,NaN,[2009-11-12],male,T20,NaN,Pakistan,20,[Imran Nazir],"[New Zealand, Pakistan]",New Zealand,field,"[Nadeem Ghauri, Zameer Haider]",Dubai International Cricket Stadium,2689

In [16]:
final_df.columns

Index(['innings', 'meta.revision', 'info.city', 'info.dates', 'info.gender',
       'info.match_type', 'info.match_type_number', 'info.outcome.winner',
       'info.overs', 'info.player_of_match', 'info.teams', 'info.toss.winner',
       'info.toss.decision', 'info.umpires', 'info.venue', 'match_id'],
      dtype='object')

In [17]:
final_df.drop(columns=['meta.revision', 'info.match_type_number' ], inplace = True)

/var/folders/qg/km03k0gn1yn690bk_brhvb3c0000gn/T/ipykernel_38011/2598767534.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(columns=['meta.revision', 'info.match_type_number' ], inplace = True)

In [18]:
final_df

,innings,info.city,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",Buenos Aires,[2023-02-28],male,T20,Bermuda,20,[KS Leverock],"[Bermuda, Panama]",Bermuda,bat,"[N Duguid, Vijaya Mallela]","Belgrano Athletic Club Ground, Buenos Aires",1
1,"[{'1st innings': {'team': 'West Indies', 'deli...",Canberra,[2020-02-26],female,T20,Pakistan,20,[Javeria Khan],"[Pakistan, West Indies]",West Indies,bat,"[CA Polosak, S George]",Manuka Oval,2
2,"[{'1st innings': {'team': 'India', 'deliveries...",Bangalore,[2016-03-15],female,T20,India,20,[H Kaur],"[India, Bangladesh]",Bangladesh,field,"[Aleem Dar, REJ Martinesz]",M Chinnaswamy Stadium,3
3,"[{'1st innings': {'team': 'Malaysia', 'deliver...",Bangi,[2023-09-01],female,T20,United Arab Emirates,20,"[KKN Egodage, KKN Egodage]","[Malaysia, United Arab Emirates]",Malaysia,bat,"[N Perera, Sarika Prasad]","UKM-YSD Cricket Oval, Bangi",4
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",Lagos,[2023-10-05],male,T20,Nigeria,20,[Sulaimon Runsewe],"[Nigeria, Sierra Leone]",Sierra Leone,field,"[M Bodie, T Oladunjoye]","Tafawa Balewa Square Cricket Oval, Lagos",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",Auckland,[2012-02-11],male,T20,New Zealand,20,[MJ Guptill],"[New Zealand, Zimbabwe]",Zimbabwe,bat,"[GAV Baxter, BG Frost]",Eden Park,2685
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Trinidad,[2017-04-01],male,T20,West Indies,20,[E Lewis],"[West Indies, Pakistan]",Pakistan,bat,"[GO Brathwaite, LS Reifer]","Queen's Park Oval, Port of Spain",2686
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Hangzhou,[2023-10-07],male,T20,Bangladesh,20,NaN,"[Pakistan, Bangladesh]",Bangladesh,field,"[Mahmood Kharoti, Sarika Prasad]",Zhejiang University of Technology Cricket Field,2687
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Nagpur,[2016-03-08],male,T20,Afghanistan,20,[Mohammad Shahzad],"[Afghanistan, Scotland]",Afghanistan,bat,"[M Erasmus, RK Illingworth]","Vidarbha Cricket Association Stadium, Jamtha",2688
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",NaN,[2009-11-12],male,T20,Pakistan,20,[Imran Nazir],"[New Zealand, Pakistan]",New Zealand,field,"[Nadeem Ghauri, Zameer Haider]",Dubai International Cricket Stadium,2689

In [19]:
final_df['info.gender'].value_counts()

info.gender
male      1783
female     906
Name: count, dtype: int64

In [20]:
final_df['info.overs'].value_counts()

info.overs
20    2685
50       4
Name: count, dtype: int64

In [21]:
backup1 = final_df.copy()

In [22]:
final_df = final_df[final_df['info.gender']=='male']
final_df.drop(columns = ['info.gender'])
final_df

,innings,info.city,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",Buenos Aires,[2023-02-28],male,T20,Bermuda,20,[KS Leverock],"[Bermuda, Panama]",Bermuda,bat,"[N Duguid, Vijaya Mallela]","Belgrano Athletic Club Ground, Buenos Aires",1
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",Lagos,[2023-10-05],male,T20,Nigeria,20,[Sulaimon Runsewe],"[Nigeria, Sierra Leone]",Sierra Leone,field,"[M Bodie, T Oladunjoye]","Tafawa Balewa Square Cricket Oval, Lagos",5
5,"[{'1st innings': {'team': 'Rwanda', 'deliverie...",Kigali City,[2021-08-21],male,T20,Ghana,20,[Amoluk Singh],"[Rwanda, Ghana]",Rwanda,bat,"[Itangishaka Olivier, Vicky Prajapati]",Gahanga International Cricket Stadium. Rwanda,6
7,"[{'1st innings': {'team': 'Nepal', 'deliveries...",Kirtipur,[2024-03-05],male,T20,Netherlands,20,[M Levitt],"[Nepal, Netherlands]",Nepal,bat,"[BB Pradhan, DN Subedi]",Tribhuvan University International Cricket Gro...,8
8,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2023-07-21],male,T20,Scotland,20,[MRJ Watt],"[Scotland, Jersey]",Jersey,field,"[J Jensen, R Black]","Grange Cricket Club Ground, Raeburn Place, Edi...",9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",Auckland,[2012-02-11],male,T20,New Zealand,20,[MJ Guptill],"[New Zealand, Zimbabwe]",Zimbabwe,bat,"[GAV Baxter, BG Frost]",Eden Park,2685
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Trinidad,[2017-04-01],male,T20,West Indies,20,[E Lewis],"[West Indies, Pakistan]",Pakistan,bat,"[GO Brathwaite, LS Reifer]","Queen's Park Oval, Port of Spain",2686
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Hangzhou,[2023-10-07],male,T20,Bangladesh,20,NaN,"[Pakistan, Bangladesh]",Bangladesh,field,"[Mahmood Kharoti, Sarika Prasad]",Zhejiang University of Technology Cricket Field,2687
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Nagpur,[2016-03-08],male,T20,Afghanistan,20,[Mohammad Shahzad],"[Afghanistan, Scotland]",Afghanistan,bat,"[M Erasmus, RK Illingworth]","Vidarbha Cricket Association Stadium, Jamtha",2688
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",NaN,[2009-11-12],male,T20,Pakistan,20,[Imran Nazir],"[New Zealand, Pakistan]",New Zealand,field,"[Nadeem Ghauri, Zameer Haider]",Dubai International Cricket Stadium,2689

In [25]:
final_df.drop(columns = ['info.gender'])

,innings,info.city,info.dates,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",Buenos Aires,[2023-02-28],T20,Bermuda,20,[KS Leverock],"[Bermuda, Panama]",Bermuda,bat,"[N Duguid, Vijaya Mallela]","Belgrano Athletic Club Ground, Buenos Aires",1
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",Lagos,[2023-10-05],T20,Nigeria,20,[Sulaimon Runsewe],"[Nigeria, Sierra Leone]",Sierra Leone,field,"[M Bodie, T Oladunjoye]","Tafawa Balewa Square Cricket Oval, Lagos",5
5,"[{'1st innings': {'team': 'Rwanda', 'deliverie...",Kigali City,[2021-08-21],T20,Ghana,20,[Amoluk Singh],"[Rwanda, Ghana]",Rwanda,bat,"[Itangishaka Olivier, Vicky Prajapati]",Gahanga International Cricket Stadium. Rwanda,6
7,"[{'1st innings': {'team': 'Nepal', 'deliveries...",Kirtipur,[2024-03-05],T20,Netherlands,20,[M Levitt],"[Nepal, Netherlands]",Nepal,bat,"[BB Pradhan, DN Subedi]",Tribhuvan University International Cricket Gro...,8
8,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2023-07-21],T20,Scotland,20,[MRJ Watt],"[Scotland, Jersey]",Jersey,field,"[J Jensen, R Black]","Grange Cricket Club Ground, Raeburn Place, Edi...",9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",Auckland,[2012-02-11],T20,New Zealand,20,[MJ Guptill],"[New Zealand, Zimbabwe]",Zimbabwe,bat,"[GAV Baxter, BG Frost]",Eden Park,2685
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Trinidad,[2017-04-01],T20,West Indies,20,[E Lewis],"[West Indies, Pakistan]",Pakistan,bat,"[GO Brathwaite, LS Reifer]","Queen's Park Oval, Port of Spain",2686
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Hangzhou,[2023-10-07],T20,Bangladesh,20,NaN,"[Pakistan, Bangladesh]",Bangladesh,field,"[Mahmood Kharoti, Sarika Prasad]",Zhejiang University of Technology Cricket Field,2687
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Nagpur,[2016-03-08],T20,Afghanistan,20,[Mohammad Shahzad],"[Afghanistan, Scotland]",Afghanistan,bat,"[M Erasmus, RK Illingworth]","Vidarbha Cricket Association Stadium, Jamtha",2688
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",NaN,[2009-11-12],T20,Pakistan,20,[Imran Nazir],"[New Zealand, Pakistan]",New Zealand,field,"[Nadeem Ghauri, Zameer Haider]",Dubai International Cricket Stadium,2689

In [26]:
final_df = final_df[final_df['info.overs']=='20']

In [27]:
final_df

Empty DataFrame
Columns: [innings, info.city, info.dates, info.gender, info.match_type, info.outcome.winner, info.overs, info.player_of_match, info.teams, info.toss.winner, info.toss.decision, info.umpires, info.venue, match_id]
Index: []

In [28]:
final_df = backup1

In [29]:
final_df

,innings,info.city,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",Buenos Aires,[2023-02-28],male,T20,Bermuda,20,[KS Leverock],"[Bermuda, Panama]",Bermuda,bat,"[N Duguid, Vijaya Mallela]","Belgrano Athletic Club Ground, Buenos Aires",1
1,"[{'1st innings': {'team': 'West Indies', 'deli...",Canberra,[2020-02-26],female,T20,Pakistan,20,[Javeria Khan],"[Pakistan, West Indies]",West Indies,bat,"[CA Polosak, S George]",Manuka Oval,2
2,"[{'1st innings': {'team': 'India', 'deliveries...",Bangalore,[2016-03-15],female,T20,India,20,[H Kaur],"[India, Bangladesh]",Bangladesh,field,"[Aleem Dar, REJ Martinesz]",M Chinnaswamy Stadium,3
3,"[{'1st innings': {'team': 'Malaysia', 'deliver...",Bangi,[2023-09-01],female,T20,United Arab Emirates,20,"[KKN Egodage, KKN Egodage]","[Malaysia, United Arab Emirates]",Malaysia,bat,"[N Perera, Sarika Prasad]","UKM-YSD Cricket Oval, Bangi",4
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",Lagos,[2023-10-05],male,T20,Nigeria,20,[Sulaimon Runsewe],"[Nigeria, Sierra Leone]",Sierra Leone,field,"[M Bodie, T Oladunjoye]","Tafawa Balewa Square Cricket Oval, Lagos",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",Auckland,[2012-02-11],male,T20,New Zealand,20,[MJ Guptill],"[New Zealand, Zimbabwe]",Zimbabwe,bat,"[GAV Baxter, BG Frost]",Eden Park,2685
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Trinidad,[2017-04-01],male,T20,West Indies,20,[E Lewis],"[West Indies, Pakistan]",Pakistan,bat,"[GO Brathwaite, LS Reifer]","Queen's Park Oval, Port of Spain",2686
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Hangzhou,[2023-10-07],male,T20,Bangladesh,20,NaN,"[Pakistan, Bangladesh]",Bangladesh,field,"[Mahmood Kharoti, Sarika Prasad]",Zhejiang University of Technology Cricket Field,2687
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Nagpur,[2016-03-08],male,T20,Afghanistan,20,[Mohammad Shahzad],"[Afghanistan, Scotland]",Afghanistan,bat,"[M Erasmus, RK Illingworth]","Vidarbha Cricket Association Stadium, Jamtha",2688
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",NaN,[2009-11-12],male,T20,Pakistan,20,[Imran Nazir],"[New Zealand, Pakistan]",New Zealand,field,"[Nadeem Ghauri, Zameer Haider]",Dubai International Cricket Stadium,2689

In [30]:
backup2 = final_df.copy()

In [31]:
final_df = final_df[final_df['info.gender']=='male']
final_df.drop(columns = ['info.gender'])
final_df

,innings,info.city,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",Buenos Aires,[2023-02-28],male,T20,Bermuda,20,[KS Leverock],"[Bermuda, Panama]",Bermuda,bat,"[N Duguid, Vijaya Mallela]","Belgrano Athletic Club Ground, Buenos Aires",1
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",Lagos,[2023-10-05],male,T20,Nigeria,20,[Sulaimon Runsewe],"[Nigeria, Sierra Leone]",Sierra Leone,field,"[M Bodie, T Oladunjoye]","Tafawa Balewa Square Cricket Oval, Lagos",5
5,"[{'1st innings': {'team': 'Rwanda', 'deliverie...",Kigali City,[2021-08-21],male,T20,Ghana,20,[Amoluk Singh],"[Rwanda, Ghana]",Rwanda,bat,"[Itangishaka Olivier, Vicky Prajapati]",Gahanga International Cricket Stadium. Rwanda,6
7,"[{'1st innings': {'team': 'Nepal', 'deliveries...",Kirtipur,[2024-03-05],male,T20,Netherlands,20,[M Levitt],"[Nepal, Netherlands]",Nepal,bat,"[BB Pradhan, DN Subedi]",Tribhuvan University International Cricket Gro...,8
8,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2023-07-21],male,T20,Scotland,20,[MRJ Watt],"[Scotland, Jersey]",Jersey,field,"[J Jensen, R Black]","Grange Cricket Club Ground, Raeburn Place, Edi...",9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",Auckland,[2012-02-11],male,T20,New Zealand,20,[MJ Guptill],"[New Zealand, Zimbabwe]",Zimbabwe,bat,"[GAV Baxter, BG Frost]",Eden Park,2685
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Trinidad,[2017-04-01],male,T20,West Indies,20,[E Lewis],"[West Indies, Pakistan]",Pakistan,bat,"[GO Brathwaite, LS Reifer]","Queen's Park Oval, Port of Spain",2686
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Hangzhou,[2023-10-07],male,T20,Bangladesh,20,NaN,"[Pakistan, Bangladesh]",Bangladesh,field,"[Mahmood Kharoti, Sarika Prasad]",Zhejiang University of Technology Cricket Field,2687
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Nagpur,[2016-03-08],male,T20,Afghanistan,20,[Mohammad Shahzad],"[Afghanistan, Scotland]",Afghanistan,bat,"[M Erasmus, RK Illingworth]","Vidarbha Cricket Association Stadium, Jamtha",2688
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",NaN,[2009-11-12],male,T20,Pakistan,20,[Imran Nazir],"[New Zealand, Pakistan]",New Zealand,field,"[Nadeem Ghauri, Zameer Haider]",Dubai International Cricket Stadium,2689

In [32]:
final_df.drop(columns = ['info.gender'])

,innings,info.city,info.dates,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",Buenos Aires,[2023-02-28],T20,Bermuda,20,[KS Leverock],"[Bermuda, Panama]",Bermuda,bat,"[N Duguid, Vijaya Mallela]","Belgrano Athletic Club Ground, Buenos Aires",1
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",Lagos,[2023-10-05],T20,Nigeria,20,[Sulaimon Runsewe],"[Nigeria, Sierra Leone]",Sierra Leone,field,"[M Bodie, T Oladunjoye]","Tafawa Balewa Square Cricket Oval, Lagos",5
5,"[{'1st innings': {'team': 'Rwanda', 'deliverie...",Kigali City,[2021-08-21],T20,Ghana,20,[Amoluk Singh],"[Rwanda, Ghana]",Rwanda,bat,"[Itangishaka Olivier, Vicky Prajapati]",Gahanga International Cricket Stadium. Rwanda,6
7,"[{'1st innings': {'team': 'Nepal', 'deliveries...",Kirtipur,[2024-03-05],T20,Netherlands,20,[M Levitt],"[Nepal, Netherlands]",Nepal,bat,"[BB Pradhan, DN Subedi]",Tribhuvan University International Cricket Gro...,8
8,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2023-07-21],T20,Scotland,20,[MRJ Watt],"[Scotland, Jersey]",Jersey,field,"[J Jensen, R Black]","Grange Cricket Club Ground, Raeburn Place, Edi...",9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",Auckland,[2012-02-11],T20,New Zealand,20,[MJ Guptill],"[New Zealand, Zimbabwe]",Zimbabwe,bat,"[GAV Baxter, BG Frost]",Eden Park,2685
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Trinidad,[2017-04-01],T20,West Indies,20,[E Lewis],"[West Indies, Pakistan]",Pakistan,bat,"[GO Brathwaite, LS Reifer]","Queen's Park Oval, Port of Spain",2686
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Hangzhou,[2023-10-07],T20,Bangladesh,20,NaN,"[Pakistan, Bangladesh]",Bangladesh,field,"[Mahmood Kharoti, Sarika Prasad]",Zhejiang University of Technology Cricket Field,2687
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Nagpur,[2016-03-08],T20,Afghanistan,20,[Mohammad Shahzad],"[Afghanistan, Scotland]",Afghanistan,bat,"[M Erasmus, RK Illingworth]","Vidarbha Cricket Association Stadium, Jamtha",2688
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",NaN,[2009-11-12],T20,Pakistan,20,[Imran Nazir],"[New Zealand, Pakistan]",New Zealand,field,"[Nadeem Ghauri, Zameer Haider]",Dubai International Cricket Stadium,2689

In [33]:
backup2 = final_df.copy()

In [35]:
final_df = final_df[final_df['info.overs']!='50']

In [40]:
final_df.drop(columns = 'info.overs')

,innings,info.city,info.dates,info.gender,info.match_type,info.outcome.winner,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",Buenos Aires,[2023-02-28],male,T20,Bermuda,[KS Leverock],"[Bermuda, Panama]",Bermuda,bat,"[N Duguid, Vijaya Mallela]","Belgrano Athletic Club Ground, Buenos Aires",1
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",Lagos,[2023-10-05],male,T20,Nigeria,[Sulaimon Runsewe],"[Nigeria, Sierra Leone]",Sierra Leone,field,"[M Bodie, T Oladunjoye]","Tafawa Balewa Square Cricket Oval, Lagos",5
5,"[{'1st innings': {'team': 'Rwanda', 'deliverie...",Kigali City,[2021-08-21],male,T20,Ghana,[Amoluk Singh],"[Rwanda, Ghana]",Rwanda,bat,"[Itangishaka Olivier, Vicky Prajapati]",Gahanga International Cricket Stadium. Rwanda,6
7,"[{'1st innings': {'team': 'Nepal', 'deliveries...",Kirtipur,[2024-03-05],male,T20,Netherlands,[M Levitt],"[Nepal, Netherlands]",Nepal,bat,"[BB Pradhan, DN Subedi]",Tribhuvan University International Cricket Gro...,8
8,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2023-07-21],male,T20,Scotland,[MRJ Watt],"[Scotland, Jersey]",Jersey,field,"[J Jensen, R Black]","Grange Cricket Club Ground, Raeburn Place, Edi...",9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",Auckland,[2012-02-11],male,T20,New Zealand,[MJ Guptill],"[New Zealand, Zimbabwe]",Zimbabwe,bat,"[GAV Baxter, BG Frost]",Eden Park,2685
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Trinidad,[2017-04-01],male,T20,West Indies,[E Lewis],"[West Indies, Pakistan]",Pakistan,bat,"[GO Brathwaite, LS Reifer]","Queen's Park Oval, Port of Spain",2686
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Hangzhou,[2023-10-07],male,T20,Bangladesh,NaN,"[Pakistan, Bangladesh]",Bangladesh,field,"[Mahmood Kharoti, Sarika Prasad]",Zhejiang University of Technology Cricket Field,2687
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Nagpur,[2016-03-08],male,T20,Afghanistan,[Mohammad Shahzad],"[Afghanistan, Scotland]",Afghanistan,bat,"[M Erasmus, RK Illingworth]","Vidarbha Cricket Association Stadium, Jamtha",2688
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",NaN,[2009-11-12],male,T20,Pakistan,[Imran Nazir],"[New Zealand, Pakistan]",New Zealand,field,"[Nadeem Ghauri, Zameer Haider]",Dubai International Cricket Stadium,2689

In [41]:
final_df.drop(columns = 'info.gender')

,innings,info.city,info.dates,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",Buenos Aires,[2023-02-28],T20,Bermuda,20,[KS Leverock],"[Bermuda, Panama]",Bermuda,bat,"[N Duguid, Vijaya Mallela]","Belgrano Athletic Club Ground, Buenos Aires",1
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",Lagos,[2023-10-05],T20,Nigeria,20,[Sulaimon Runsewe],"[Nigeria, Sierra Leone]",Sierra Leone,field,"[M Bodie, T Oladunjoye]","Tafawa Balewa Square Cricket Oval, Lagos",5
5,"[{'1st innings': {'team': 'Rwanda', 'deliverie...",Kigali City,[2021-08-21],T20,Ghana,20,[Amoluk Singh],"[Rwanda, Ghana]",Rwanda,bat,"[Itangishaka Olivier, Vicky Prajapati]",Gahanga International Cricket Stadium. Rwanda,6
7,"[{'1st innings': {'team': 'Nepal', 'deliveries...",Kirtipur,[2024-03-05],T20,Netherlands,20,[M Levitt],"[Nepal, Netherlands]",Nepal,bat,"[BB Pradhan, DN Subedi]",Tribhuvan University International Cricket Gro...,8
8,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2023-07-21],T20,Scotland,20,[MRJ Watt],"[Scotland, Jersey]",Jersey,field,"[J Jensen, R Black]","Grange Cricket Club Ground, Raeburn Place, Edi...",9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",Auckland,[2012-02-11],T20,New Zealand,20,[MJ Guptill],"[New Zealand, Zimbabwe]",Zimbabwe,bat,"[GAV Baxter, BG Frost]",Eden Park,2685
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Trinidad,[2017-04-01],T20,West Indies,20,[E Lewis],"[West Indies, Pakistan]",Pakistan,bat,"[GO Brathwaite, LS Reifer]","Queen's Park Oval, Port of Spain",2686
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Hangzhou,[2023-10-07],T20,Bangladesh,20,NaN,"[Pakistan, Bangladesh]",Bangladesh,field,"[Mahmood Kharoti, Sarika Prasad]",Zhejiang University of Technology Cricket Field,2687
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Nagpur,[2016-03-08],T20,Afghanistan,20,[Mohammad Shahzad],"[Afghanistan, Scotland]",Afghanistan,bat,"[M Erasmus, RK Illingworth]","Vidarbha Cricket Association Stadium, Jamtha",2688
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",NaN,[2009-11-12],T20,Pakistan,20,[Imran Nazir],"[New Zealand, Pakistan]",New Zealand,field,"[Nadeem Ghauri, Zameer Haider]",Dubai International Cricket Stadium,2689

In [42]:
final_df

,innings,info.city,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",Buenos Aires,[2023-02-28],male,T20,Bermuda,20,[KS Leverock],"[Bermuda, Panama]",Bermuda,bat,"[N Duguid, Vijaya Mallela]","Belgrano Athletic Club Ground, Buenos Aires",1
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",Lagos,[2023-10-05],male,T20,Nigeria,20,[Sulaimon Runsewe],"[Nigeria, Sierra Leone]",Sierra Leone,field,"[M Bodie, T Oladunjoye]","Tafawa Balewa Square Cricket Oval, Lagos",5
5,"[{'1st innings': {'team': 'Rwanda', 'deliverie...",Kigali City,[2021-08-21],male,T20,Ghana,20,[Amoluk Singh],"[Rwanda, Ghana]",Rwanda,bat,"[Itangishaka Olivier, Vicky Prajapati]",Gahanga International Cricket Stadium. Rwanda,6
7,"[{'1st innings': {'team': 'Nepal', 'deliveries...",Kirtipur,[2024-03-05],male,T20,Netherlands,20,[M Levitt],"[Nepal, Netherlands]",Nepal,bat,"[BB Pradhan, DN Subedi]",Tribhuvan University International Cricket Gro...,8
8,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2023-07-21],male,T20,Scotland,20,[MRJ Watt],"[Scotland, Jersey]",Jersey,field,"[J Jensen, R Black]","Grange Cricket Club Ground, Raeburn Place, Edi...",9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",Auckland,[2012-02-11],male,T20,New Zealand,20,[MJ Guptill],"[New Zealand, Zimbabwe]",Zimbabwe,bat,"[GAV Baxter, BG Frost]",Eden Park,2685
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Trinidad,[2017-04-01],male,T20,West Indies,20,[E Lewis],"[West Indies, Pakistan]",Pakistan,bat,"[GO Brathwaite, LS Reifer]","Queen's Park Oval, Port of Spain",2686
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Hangzhou,[2023-10-07],male,T20,Bangladesh,20,NaN,"[Pakistan, Bangladesh]",Bangladesh,field,"[Mahmood Kharoti, Sarika Prasad]",Zhejiang University of Technology Cricket Field,2687
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Nagpur,[2016-03-08],male,T20,Afghanistan,20,[Mohammad Shahzad],"[Afghanistan, Scotland]",Afghanistan,bat,"[M Erasmus, RK Illingworth]","Vidarbha Cricket Association Stadium, Jamtha",2688
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",NaN,[2009-11-12],male,T20,Pakistan,20,[Imran Nazir],"[New Zealand, Pakistan]",New Zealand,field,"[Nadeem Ghauri, Zameer Haider]",Dubai International Cricket Stadium,2689

In [44]:
final_df['info.gender'].value_counts()

info.gender
male    1783
Name: count, dtype: int64

In [45]:
final_df['info.overs'].value_counts()

info.overs
20    1783
Name: count, dtype: int64

In [46]:
final_df = final_df.drop(columns = ['info.gender', 'info.overs'], inplace = True)

In [49]:
backup2

,innings,info.city,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",Buenos Aires,[2023-02-28],male,T20,Bermuda,20,[KS Leverock],"[Bermuda, Panama]",Bermuda,bat,"[N Duguid, Vijaya Mallela]","Belgrano Athletic Club Ground, Buenos Aires",1
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",Lagos,[2023-10-05],male,T20,Nigeria,20,[Sulaimon Runsewe],"[Nigeria, Sierra Leone]",Sierra Leone,field,"[M Bodie, T Oladunjoye]","Tafawa Balewa Square Cricket Oval, Lagos",5
5,"[{'1st innings': {'team': 'Rwanda', 'deliverie...",Kigali City,[2021-08-21],male,T20,Ghana,20,[Amoluk Singh],"[Rwanda, Ghana]",Rwanda,bat,"[Itangishaka Olivier, Vicky Prajapati]",Gahanga International Cricket Stadium. Rwanda,6
7,"[{'1st innings': {'team': 'Nepal', 'deliveries...",Kirtipur,[2024-03-05],male,T20,Netherlands,20,[M Levitt],"[Nepal, Netherlands]",Nepal,bat,"[BB Pradhan, DN Subedi]",Tribhuvan University International Cricket Gro...,8
8,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2023-07-21],male,T20,Scotland,20,[MRJ Watt],"[Scotland, Jersey]",Jersey,field,"[J Jensen, R Black]","Grange Cricket Club Ground, Raeburn Place, Edi...",9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",Auckland,[2012-02-11],male,T20,New Zealand,20,[MJ Guptill],"[New Zealand, Zimbabwe]",Zimbabwe,bat,"[GAV Baxter, BG Frost]",Eden Park,2685
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Trinidad,[2017-04-01],male,T20,West Indies,20,[E Lewis],"[West Indies, Pakistan]",Pakistan,bat,"[GO Brathwaite, LS Reifer]","Queen's Park Oval, Port of Spain",2686
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Hangzhou,[2023-10-07],male,T20,Bangladesh,20,NaN,"[Pakistan, Bangladesh]",Bangladesh,field,"[Mahmood Kharoti, Sarika Prasad]",Zhejiang University of Technology Cricket Field,2687
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Nagpur,[2016-03-08],male,T20,Afghanistan,20,[Mohammad Shahzad],"[Afghanistan, Scotland]",Afghanistan,bat,"[M Erasmus, RK Illingworth]","Vidarbha Cricket Association Stadium, Jamtha",2688
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",NaN,[2009-11-12],male,T20,Pakistan,20,[Imran Nazir],"[New Zealand, Pakistan]",New Zealand,field,"[Nadeem Ghauri, Zameer Haider]",Dubai International Cricket Stadium,2689

In [53]:
final_df = backup1[backup1['info.gender']=='male']

In [62]:
final_df = backup1[backup1['info.gender']=='male']

In [63]:
final_df

,innings,info.city,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",Buenos Aires,[2023-02-28],male,T20,Bermuda,20,[KS Leverock],"[Bermuda, Panama]",Bermuda,bat,"[N Duguid, Vijaya Mallela]","Belgrano Athletic Club Ground, Buenos Aires",1
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",Lagos,[2023-10-05],male,T20,Nigeria,20,[Sulaimon Runsewe],"[Nigeria, Sierra Leone]",Sierra Leone,field,"[M Bodie, T Oladunjoye]","Tafawa Balewa Square Cricket Oval, Lagos",5
5,"[{'1st innings': {'team': 'Rwanda', 'deliverie...",Kigali City,[2021-08-21],male,T20,Ghana,20,[Amoluk Singh],"[Rwanda, Ghana]",Rwanda,bat,"[Itangishaka Olivier, Vicky Prajapati]",Gahanga International Cricket Stadium. Rwanda,6
7,"[{'1st innings': {'team': 'Nepal', 'deliveries...",Kirtipur,[2024-03-05],male,T20,Netherlands,20,[M Levitt],"[Nepal, Netherlands]",Nepal,bat,"[BB Pradhan, DN Subedi]",Tribhuvan University International Cricket Gro...,8
8,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2023-07-21],male,T20,Scotland,20,[MRJ Watt],"[Scotland, Jersey]",Jersey,field,"[J Jensen, R Black]","Grange Cricket Club Ground, Raeburn Place, Edi...",9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",Auckland,[2012-02-11],male,T20,New Zealand,20,[MJ Guptill],"[New Zealand, Zimbabwe]",Zimbabwe,bat,"[GAV Baxter, BG Frost]",Eden Park,2685
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Trinidad,[2017-04-01],male,T20,West Indies,20,[E Lewis],"[West Indies, Pakistan]",Pakistan,bat,"[GO Brathwaite, LS Reifer]","Queen's Park Oval, Port of Spain",2686
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Hangzhou,[2023-10-07],male,T20,Bangladesh,20,NaN,"[Pakistan, Bangladesh]",Bangladesh,field,"[Mahmood Kharoti, Sarika Prasad]",Zhejiang University of Technology Cricket Field,2687
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Nagpur,[2016-03-08],male,T20,Afghanistan,20,[Mohammad Shahzad],"[Afghanistan, Scotland]",Afghanistan,bat,"[M Erasmus, RK Illingworth]","Vidarbha Cricket Association Stadium, Jamtha",2688
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",NaN,[2009-11-12],male,T20,Pakistan,20,[Imran Nazir],"[New Zealand, Pakistan]",New Zealand,field,"[Nadeem Ghauri, Zameer Haider]",Dubai International Cricket Stadium,2689

In [66]:
backup = final_df.copy()

In [67]:
backup

,innings,info.city,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",Buenos Aires,[2023-02-28],male,T20,Bermuda,20,[KS Leverock],"[Bermuda, Panama]",Bermuda,bat,"[N Duguid, Vijaya Mallela]","Belgrano Athletic Club Ground, Buenos Aires",1
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",Lagos,[2023-10-05],male,T20,Nigeria,20,[Sulaimon Runsewe],"[Nigeria, Sierra Leone]",Sierra Leone,field,"[M Bodie, T Oladunjoye]","Tafawa Balewa Square Cricket Oval, Lagos",5
5,"[{'1st innings': {'team': 'Rwanda', 'deliverie...",Kigali City,[2021-08-21],male,T20,Ghana,20,[Amoluk Singh],"[Rwanda, Ghana]",Rwanda,bat,"[Itangishaka Olivier, Vicky Prajapati]",Gahanga International Cricket Stadium. Rwanda,6
7,"[{'1st innings': {'team': 'Nepal', 'deliveries...",Kirtipur,[2024-03-05],male,T20,Netherlands,20,[M Levitt],"[Nepal, Netherlands]",Nepal,bat,"[BB Pradhan, DN Subedi]",Tribhuvan University International Cricket Gro...,8
8,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2023-07-21],male,T20,Scotland,20,[MRJ Watt],"[Scotland, Jersey]",Jersey,field,"[J Jensen, R Black]","Grange Cricket Club Ground, Raeburn Place, Edi...",9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",Auckland,[2012-02-11],male,T20,New Zealand,20,[MJ Guptill],"[New Zealand, Zimbabwe]",Zimbabwe,bat,"[GAV Baxter, BG Frost]",Eden Park,2685
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Trinidad,[2017-04-01],male,T20,West Indies,20,[E Lewis],"[West Indies, Pakistan]",Pakistan,bat,"[GO Brathwaite, LS Reifer]","Queen's Park Oval, Port of Spain",2686
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Hangzhou,[2023-10-07],male,T20,Bangladesh,20,NaN,"[Pakistan, Bangladesh]",Bangladesh,field,"[Mahmood Kharoti, Sarika Prasad]",Zhejiang University of Technology Cricket Field,2687
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Nagpur,[2016-03-08],male,T20,Afghanistan,20,[Mohammad Shahzad],"[Afghanistan, Scotland]",Afghanistan,bat,"[M Erasmus, RK Illingworth]","Vidarbha Cricket Association Stadium, Jamtha",2688
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",NaN,[2009-11-12],male,T20,Pakistan,20,[Imran Nazir],"[New Zealand, Pakistan]",New Zealand,field,"[Nadeem Ghauri, Zameer Haider]",Dubai International Cricket Stadium,2689

In [68]:
final_df.drop(columns = ['info.gender'],inplace = True)

/var/folders/qg/km03k0gn1yn690bk_brhvb3c0000gn/T/ipykernel_38011/3971679261.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(columns = ['info.gender'],inplace = True)

In [70]:
final_df.drop(columns = ['info.overs'],inplace = True)

/var/folders/qg/km03k0gn1yn690bk_brhvb3c0000gn/T/ipykernel_38011/247875397.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(columns = ['info.overs'],inplace = True)

In [71]:
final_df

,innings,info.city,info.dates,info.match_type,info.outcome.winner,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",Buenos Aires,[2023-02-28],T20,Bermuda,[KS Leverock],"[Bermuda, Panama]",Bermuda,bat,"[N Duguid, Vijaya Mallela]","Belgrano Athletic Club Ground, Buenos Aires",1
4,"[{'1st innings': {'team': 'Nigeria', 'deliveri...",Lagos,[2023-10-05],T20,Nigeria,[Sulaimon Runsewe],"[Nigeria, Sierra Leone]",Sierra Leone,field,"[M Bodie, T Oladunjoye]","Tafawa Balewa Square Cricket Oval, Lagos",5
5,"[{'1st innings': {'team': 'Rwanda', 'deliverie...",Kigali City,[2021-08-21],T20,Ghana,[Amoluk Singh],"[Rwanda, Ghana]",Rwanda,bat,"[Itangishaka Olivier, Vicky Prajapati]",Gahanga International Cricket Stadium. Rwanda,6
7,"[{'1st innings': {'team': 'Nepal', 'deliveries...",Kirtipur,[2024-03-05],T20,Netherlands,[M Levitt],"[Nepal, Netherlands]",Nepal,bat,"[BB Pradhan, DN Subedi]",Tribhuvan University International Cricket Gro...,8
8,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2023-07-21],T20,Scotland,[MRJ Watt],"[Scotland, Jersey]",Jersey,field,"[J Jensen, R Black]","Grange Cricket Club Ground, Raeburn Place, Edi...",9
...,...,...,...,...,...,...,...,...,...,...,...,...
2684,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",Auckland,[2012-02-11],T20,New Zealand,[MJ Guptill],"[New Zealand, Zimbabwe]",Zimbabwe,bat,"[GAV Baxter, BG Frost]",Eden Park,2685
2685,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Trinidad,[2017-04-01],T20,West Indies,[E Lewis],"[West Indies, Pakistan]",Pakistan,bat,"[GO Brathwaite, LS Reifer]","Queen's Park Oval, Port of Spain",2686
2686,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Hangzhou,[2023-10-07],T20,Bangladesh,NaN,"[Pakistan, Bangladesh]",Bangladesh,field,"[Mahmood Kharoti, Sarika Prasad]",Zhejiang University of Technology Cricket Field,2687
2687,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Nagpur,[2016-03-08],T20,Afghanistan,[Mohammad Shahzad],"[Afghanistan, Scotland]",Afghanistan,bat,"[M Erasmus, RK Illingworth]","Vidarbha Cricket Association Stadium, Jamtha",2688
2688,"[{'1st innings': {'team': 'Pakistan', 'deliver...",NaN,[2009-11-12],T20,Pakistan,[Imran Nazir],"[New Zealand, Pakistan]",New Zealand,field,"[Nadeem Ghauri, Zameer Haider]",Dubai International Cricket Stadium,2689

In [72]:
final_df['info.match_type'].value_counts()

info.match_type
T20    1783
Name: count, dtype: int64

In [79]:
import pickle
pickle.dump(final_df, open('dataset_level1.pkl11','wb'))

In [74]:
# Extracting only 1st innings data here onwards

In [81]:
matches = pickle.load(open('dataset_level1.pkl11','rb'))

In [91]:
matches.iloc[0]['innings'][0]['1st innings']['deliveries']

[{0.1: {'bowler': 'AM Patel',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'non_striker': 'T Manders',
   'batsman': 'KS Leverock'}},
 {0.2: {'bowler': 'AM Patel',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'non_striker': 'T Manders',
   'batsman': 'KS Leverock'}},
 {0.3: {'bowler': 'AM Patel',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'non_striker': 'T Manders',
   'batsman': 'KS Leverock'}},
 {0.4: {'bowler': 'AM Patel',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'non_striker': 'T Manders',
   'batsman': 'KS Leverock'}},
 {0.5: {'bowler': 'AM Patel',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'non_striker': 'T Manders',
   'batsman': 'KS Leverock'}},
 {0.6: {'bowler': 'AM Patel',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'non_striker': 'T Manders',
   'batsman': 'KS Leverock'}},
 {0.7: {'bowler': 'AM Patel',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'non_striker': 'T Manders',
   'batsman': 'KS Leverock'}},
 {0.8: {'bowler': 'AM Patel',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'non_striker': 'T Manders',
   'batsman': 'KS Leverock'}},
 {0.9: {'non_striker': 'T Manders',
   'bowler': 'AM Patel',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'KS Leverock'}},
 {1.1: {'non_striker': 'KS Leverock',
   'bowler': 'KB Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {1.2: {'non_striker': 'KS Leverock',
   'bowler': 'KB Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {1.3: {'non_striker': 'KS Leverock',
   'bowler': 'KB Ahir',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'T Manders'}},
 {1.4: {'non_striker': 'KS Leverock',
   'bowler': 'KB Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {1.5: {'non_striker': 'T Manders',
   'bowler': 'KB Ahir',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'KS Leverock'}},
 {1.6: {'non_striker': 'T Manders',
   'bowler': 'KB Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {1.7: {'non_striker': 'KS Leverock',
   'bowler': 'KB Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {2.1: {'non_striker': 'T Manders',
   'bowler': 'N Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KS Leverock'}},
 {2.2: {'non_striker': 'T Manders',
   'bowler': 'N Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {2.3: {'non_striker': 'KS Leverock',
   'bowler': 'N Ahir',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'T Manders'}},
 {2.4: {'non_striker': 'KS Leverock',
   'bowler': 'N Ahir',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'T Manders'}},
 {2.5: {'non_striker': 'KS Leverock',
   'bowler': 'N Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {2.6: {'non_striker': 'T Manders',
   'bowler': 'N Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {3.1: {'non_striker': 'T Manders',
   'bowler': 'KB Ahir',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'KS Leverock'}},
 {3.2: {'non_striker': 'T Manders',
   'bowler': 'KB Ahir',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'KS Leverock'}},
 {3.3: {'non_striker': 'T Manders',
   'bowler': 'KB Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KS Leverock'}},
 {3.4: {'non_striker': 'T Manders',
   'bowler': 'KB Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KS Leverock'}},
 {3.5: {'non_striker': 'T Manders',
   'bowler': 'KB Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {3.6: {'non_striker': 'KS Leverock',
   'bowler': 'KB Ahir',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'T Manders'}},
 {3.7: {'non_striker': 'KS Leverock',
   'bowler': 'KB Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {4.1: {'non_striker': 'KS Leverock',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'T Manders'}},
 {4.2: {'non_striker': 'KS Leverock',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'T Manders'}},
 {4.3: {'non_striker': 'KS Leverock',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {4.4: {'non_striker': 'T Manders',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'KS Leverock'}},
 {4.5: {'non_striker': 'T Manders',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'KS Leverock'}},
 {4.6: {'non_striker': 'T Manders',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KS Leverock'}},
 {5.1: {'non_striker': 'KS Leverock',
   'bowler': 'Sohel Patel',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {5.2: {'non_striker': 'T Manders',
   'bowler': 'Sohel Patel',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {5.3: {'non_striker': 'KS Leverock',
   'bowler': 'Sohel Patel',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {5.4: {'non_striker': 'KS Leverock',
   'bowler': 'Sohel Patel',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {5.5: {'non_striker': 'KS Leverock',
   'bowler': 'Sohel Patel',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {5.6: {'non_striker': 'KS Leverock',
   'bowler': 'Sohel Patel',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {6.1: {'non_striker': 'T Manders',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KS Leverock'}},
 {6.2: {'non_striker': 'T Manders',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {6.3: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {6.4: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {6.5: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {6.6: {'non_striker': 'T Manders',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {7.1: {'non_striker': 'T Manders',
   'bowler': 'Sohel Patel',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KS Leverock'}},
 {7.2: {'non_striker': 'T Manders',
   'bowler': 'Sohel Patel',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {7.3: {'non_striker': 'KS Leverock',
   'bowler': 'Sohel Patel',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {7.4: {'non_striker': 'T Manders',
   'bowler': 'Sohel Patel',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'KS Leverock'}},
 {7.5: {'non_striker': 'T Manders',
   'bowler': 'Sohel Patel',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'KS Leverock'}},
 {7.6: {'non_striker': 'T Manders',
   'bowler': 'Sohel Patel',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KS Leverock'}},
 {8.1: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {8.2: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {8.3: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {8.4: {'non_striker': 'T Manders',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {8.5: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'T Manders'}},
 {8.6: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {9.1: {'non_striker': 'KS Leverock',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {9.2: {'non_striker': 'KS Leverock',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'T Manders'}},
 {9.3: {'non_striker': 'KS Leverock',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {9.4: {'non_striker': 'KS Leverock',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {9.5: {'non_striker': 'T Manders',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KS Leverock'}},
 {9.6: {'non_striker': 'T Manders',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'KS Leverock'}},
 {10.1: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'T Manders'}},
 {10.2: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'T Manders'}},
 {10.3: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {10.4: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {10.5: {'non_striker': 'T Manders',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {10.6: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'T Manders'}},
 {10.7: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {11.1: {'non_striker': 'KS Leverock',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {11.2: {'non_striker': 'KS Leverock',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {11.3: {'non_striker': 'T Manders',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'KS Leverock'}},
 {11.4: {'non_striker': 'T Manders',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {11.5: {'non_striker': 'KS Leverock',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {11.6: {'non_striker': 'T Manders',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'KS Leverock'}},
 {12.1: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {12.2: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {12.3: {'non_striker': 'T Manders',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 2, 'total': 2, 'batsman': 0},
   'extras': {'wides': 2},
   'batsman': 'KS Leverock'}},
 {12.4: {'non_striker': 'KS Leverock',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {12.5: {'non_striker': 'T Manders',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KS Leverock'}},
 {12.6: {'non_striker': 'T Manders',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'KS Leverock'}},
 {12.7: {'non_striker': 'T Manders',
   'bowler': 'Irfan Hafejee',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {13.1: {'non_striker': 'T Manders',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {13.2: {'non_striker': 'KS Leverock',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {13.3: {'non_striker': 'T Manders',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'KS Leverock'}},
 {13.4: {'non_striker': 'T Manders',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {13.5: {'non_striker': 'KS Leverock',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {13.6: {'non_striker': 'T Manders',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KS Leverock'}},
 {14.1: {'non_striker': 'KS Leverock',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {14.2: {'non_striker': 'T Manders',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KS Leverock'}},
 {14.3: {'non_striker': 'T Manders',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'KS Leverock'}},
 {14.4: {'non_striker': 'T Manders',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 4, 'total': 4, 'batsman': 0},
   'extras': {'byes': 4},
   'batsman': 'KS Leverock'}},
 {14.5: {'non_striker': 'T Manders',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {14.6: {'non_striker': 'KS Leverock',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {15.1: {'non_striker': 'T Manders',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KS Leverock'}},
 {15.2: {'non_striker': 'T Manders',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {15.3: {'non_striker': 'KS Leverock',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {15.4: {'non_striker': 'T Manders',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'KS Leverock'}},
 {15.5: {'non_striker': 'T Manders',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KS Leverock'}},
 {15.6: {'non_striker': 'T Manders',
   'bowler': 'VC Ahir',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'KS Leverock'}},
 {16.1: {'non_striker': 'KS Leverock',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {16.2: {'non_striker': 'KS Leverock',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {16.3: {'non_striker': 'T Manders',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {16.4: {'non_striker': 'KS Leverock',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'legbyes': 1},
   'batsman': 'T Manders'}},
 {16.5: {'non_striker': 'T Manders',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'KS Leverock'}},
 {16.6: {'non_striker': 'T Manders',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'KS Leverock'}},
 {17.1: {'non_striker': 'KS Leverock',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 3, 'batsman': 3},
   'batsman': 'T Manders'}},
 {17.2: {'non_striker': 'T Manders',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {17.3: {'non_striker': 'KS Leverock',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {17.4: {'non_striker': 'T Manders',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'KS Leverock'}},
 {17.5: {'non_striker': 'T Manders',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KS Leverock'}},
 {17.6: {'non_striker': 'KS Leverock',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {18.1: {'non_striker': 'T Manders',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KS Leverock',
   'wicket': {'player_out': 'KS Leverock',
    'fielders': ['M Sohel Patel'],
    'kind': 'caught'}}},
 {18.2: {'non_striker': 'T Manders',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DMW Rawlins'}},
 {18.3: {'non_striker': 'DMW Rawlins',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {18.4: {'non_striker': 'T Manders',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DMW Rawlins'}},
 {18.5: {'non_striker': 'DMW Rawlins',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'T Manders'}},
 {18.6: {'non_striker': 'DMW Rawlins',
   'bowler': 'A Natubhai Ahir',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'T Manders'}},
 {19.1: {'non_striker': 'T Manders',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'DMW Rawlins'}},
 {19.2: {'non_striker': 'T Manders',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 2, 'total': 2, 'batsman': 0},
   'extras': {'byes': 2},
   'batsman': 'DMW Rawlins'}},
 {19.3: {'non_striker': 'T Manders',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DMW Rawlins'}},
 {19.4: {'non_striker': 'T Manders',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DMW Rawlins'}},
 {19.5: {'non_striker': 'DMW Rawlins',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'T Manders'}},
 {19.6: {'non_striker': 'T Manders',
   'bowler': 'RDB Ahir',
   'runs': {'extras': 4, 'total': 4, 'batsman': 0},
   'extras': {'legbyes': 4},
   'batsman': 'DMW Rawlins'}}]

In [95]:
count = 1
delivery_df = pd.DataFrame()
for index, row in matches.iterrows():
    if count in [75,108,150,180,268,360,443,458,584,748,982,1052,1111,1226,1345]:
        count += 1
        continue
    count += 1
    ball_of_match = []
    batsman = []
    bowler = []
    runs = []
    player_of_dismissed = []
    teams = []
    batting_team = []
    match_id = []
    city = []
    venue = []
    for ball in row['innings'][0]['1st innings']['deliveries']:
        for key in ball.keys():
            match_id.append(count)
            batting_team.append(row['innings'][0]['1st innings']['team'])
            teams.append(row['info.teams'])
            ball_of_match.append(key)
            batsman.append(ball[key]['batsman'])
            bowler.append(ball[key]['bowler'])
            runs.append(ball[key]['runs']['total'])
            city.append(row['info.city'])
            venue.append(row['info.venue'])
            try:
                player_of_dismissed.append(ball[key]['wicket']['player_out'])
            except KeyError:
                player_of_dismissed.append('0')
    loop_df = pd.DataFrame({
        'match_id': match_id,
        'teams': teams,
        'batting_team': batting_team,
        'ball': ball_of_match,
        'batsman': batsman,
        'bowler': bowler,
        'runs': runs,
        'player_dismissed': player_of_dismissed,
        'city': city,
        'venue': venue
    })
    delivery_df = pd.concat([delivery_df, loop_df], ignore_index=True)

In [96]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,2,"[Bermuda, Panama]",Bermuda,0.1,KS Leverock,AM Patel,1,0,Buenos Aires,"Belgrano Athletic Club Ground, Buenos Aires"
1,2,"[Bermuda, Panama]",Bermuda,0.2,KS Leverock,AM Patel,0,0,Buenos Aires,"Belgrano Athletic Club Ground, Buenos Aires"
2,2,"[Bermuda, Panama]",Bermuda,0.3,KS Leverock,AM Patel,0,0,Buenos Aires,"Belgrano Athletic Club Ground, Buenos Aires"
3,2,"[Bermuda, Panama]",Bermuda,0.4,KS Leverock,AM Patel,1,0,Buenos Aires,"Belgrano Athletic Club Ground, Buenos Aires"
4,2,"[Bermuda, Panama]",Bermuda,0.5,KS Leverock,AM Patel,0,0,Buenos Aires,"Belgrano Athletic Club Ground, Buenos Aires"
...,...,...,...,...,...,...,...,...,...,...
214645,1784,"[New Zealand, Pakistan]",Pakistan,19.2,Sohail Tanvir,TG Southee,6,0,NaN,Dubai International Cricket Stadium
214646,1784,"[New Zealand, Pakistan]",Pakistan,19.3,Sohail Tanvir,TG Southee,0,Sohail Tanvir,NaN,Dubai International Cricket Stadium
214647,1784,"[New Zealand, Pakistan]",Pakistan,19.4,Abdul Razzaq,TG Southee,1,0,NaN,Dubai International Cricket Stadium
214648,1784,"[New Zealand, Pakistan]",Pakistan,19.5,Mohammad Amir,TG Southee,2,0,NaN,Dubai International Cricket Stadium
214649,1784,"[New Zealand, Pakistan]",Pakistan,19.6,Mohammad Amir,TG Southee,0,Mohammad Amir,NaN,Dubai International Cricket Stadium

In [97]:
# Feature Engineering

In [99]:
def bowl(row):
    for team in row['teams']:
        if team != row['batting_team']:
            return team

In [100]:
delivery_df['bowling_team'] = delivery_df.apply(bowl, axis=1)

In [102]:
backup = delivery_df.copy()

In [104]:
delivery_df.drop(columns = 'teams', inplace = True)

In [105]:
delivery_df

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,Bermuda,0.1,KS Leverock,AM Patel,1,0,Buenos Aires,"Belgrano Athletic Club Ground, Buenos Aires",Panama
1,2,Bermuda,0.2,KS Leverock,AM Patel,0,0,Buenos Aires,"Belgrano Athletic Club Ground, Buenos Aires",Panama
2,2,Bermuda,0.3,KS Leverock,AM Patel,0,0,Buenos Aires,"Belgrano Athletic Club Ground, Buenos Aires",Panama
3,2,Bermuda,0.4,KS Leverock,AM Patel,1,0,Buenos Aires,"Belgrano Athletic Club Ground, Buenos Aires",Panama
4,2,Bermuda,0.5,KS Leverock,AM Patel,0,0,Buenos Aires,"Belgrano Athletic Club Ground, Buenos Aires",Panama
...,...,...,...,...,...,...,...,...,...,...
214645,1784,Pakistan,19.2,Sohail Tanvir,TG Southee,6,0,NaN,Dubai International Cricket Stadium,New Zealand
214646,1784,Pakistan,19.3,Sohail Tanvir,TG Southee,0,Sohail Tanvir,NaN,Dubai International Cricket Stadium,New Zealand
214647,1784,Pakistan,19.4,Abdul Razzaq,TG Southee,1,0,NaN,Dubai International Cricket Stadium,New Zealand
214648,1784,Pakistan,19.5,Mohammad Amir,TG Southee,2,0,NaN,Dubai International Cricket Stadium,New Zealand
214649,1784,Pakistan,19.6,Mohammad Amir,TG Southee,0,Mohammad Amir,NaN,Dubai International Cricket Stadium,New Zealand

In [114]:
delivery_df['batting_team'].unique()

array(['Bermuda', 'Nigeria', 'Rwanda', 'Nepal', 'Scotland', 'Netherlands',
       'Oman', 'West Indies', 'Malta', 'Canada', 'Swaziland', 'India',
       'England', 'South Africa', 'Argentina', 'Ghana', 'Portugal',
       'Pakistan', 'Zimbabwe', 'Bahrain', 'Bangladesh', 'Isle of Man',
       'Cameroon', 'New Zealand', 'Spain', 'Indonesia', 'Afghanistan',
       'Gibraltar', 'Tanzania', 'China', 'Maldives', 'Kenya', 'Slovenia',
       'Hungary', 'Romania', 'Bhutan', 'Czech Republic', 'Australia',
       'Kuwait', 'Malaysia', 'United Arab Emirates', 'Ireland',
       'Hong Kong', 'Denmark', 'Mali', 'Bulgaria', 'Austria', 'Botswana',
       'Saudi Arabia', 'Vanuatu', 'Japan', 'Panama', 'Thailand',
       'Sri Lanka', 'Luxembourg', 'Singapore', 'Papua New Guinea',
       'Finland', 'Germany', 'Uganda', 'Croatia', 'France', 'Serbia',
       'Fiji', 'Cyprus', 'Belgium', 'Sweden', 'Guernsey', 'Namibia',
       'United States of America', 'Italy', 'Jersey', 'Mexico',
       'Sierra Leone', 'Qatar', 'Estonia', 'Bahamas', 'Seychelles',
       'Samoa', 'Belize', 'Cayman Islands', 'Philippines', 'St Helena',
       'Norway', 'Mozambique', 'Chile', 'Malawi', 'Gambia', 'Switzerland',
       'Israel', 'Cambodia', 'Turkey', 'Lesotho', 'Cook Islands',
       'Myanmar', 'South Korea', 'Iran'], dtype=object)

In [112]:
len(delivery_df['bowling_team'].unique())

98

In [115]:
teams = [
    'Australia',
    'India',
    'Bangladesh',
    'West Indies',
    'Nepal',
    'Scotland',
    'Netherlands',
    'Canada',
    'England',
    'South Africa',
    'Oman',
    'Pakistan',
    'New Zealand',
    'Afghanistan',
    'Ireland',
    'Sri Lanka',
    'United States of America',
    'Papua New Guinea',
    'Uganda',
    'Namibia',
]

In [116]:
delivery_df = delivery_df[delivery_df['batting_team'].isin(teams)]
delivery_df = delivery_df[delivery_df['bowling_team'].isin(teams)]

In [117]:
delivery_df

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
373,5,Nepal,0.1,K Bhurtel,VJ Kingma,0,0,Kirtipur,Tribhuvan University International Cricket Gro...,Netherlands
374,5,Nepal,0.2,K Bhurtel,VJ Kingma,1,0,Kirtipur,Tribhuvan University International Cricket Gro...,Netherlands
375,5,Nepal,0.3,Aasif Sheikh,VJ Kingma,0,0,Kirtipur,Tribhuvan University International Cricket Gro...,Netherlands
376,5,Nepal,0.4,Aasif Sheikh,VJ Kingma,0,0,Kirtipur,Tribhuvan University International Cricket Gro...,Netherlands
377,5,Nepal,0.5,Aasif Sheikh,VJ Kingma,0,0,Kirtipur,Tribhuvan University International Cricket Gro...,Netherlands
...,...,...,...,...,...,...,...,...,...,...
214645,1784,Pakistan,19.2,Sohail Tanvir,TG Southee,6,0,NaN,Dubai International Cricket Stadium,New Zealand
214646,1784,Pakistan,19.3,Sohail Tanvir,TG Southee,0,Sohail Tanvir,NaN,Dubai International Cricket Stadium,New Zealand
214647,1784,Pakistan,19.4,Abdul Razzaq,TG Southee,1,0,NaN,Dubai International Cricket Stadium,New Zealand
214648,1784,Pakistan,19.5,Mohammad Amir,TG Southee,2,0,NaN,Dubai International Cricket Stadium,New Zealand
214649,1784,Pakistan,19.6,Mohammad Amir,TG Southee,0,Mohammad Amir,NaN,Dubai International Cricket Stadium,New Zealand

In [119]:
output = delivery_df[['match_id','batting_team','bowling_team','ball','runs','player_dismissed','city','venue']]
output

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
373,5,Nepal,Netherlands,0.1,0,0,Kirtipur,Tribhuvan University International Cricket Gro...
374,5,Nepal,Netherlands,0.2,1,0,Kirtipur,Tribhuvan University International Cricket Gro...
375,5,Nepal,Netherlands,0.3,0,0,Kirtipur,Tribhuvan University International Cricket Gro...
376,5,Nepal,Netherlands,0.4,0,0,Kirtipur,Tribhuvan University International Cricket Gro...
377,5,Nepal,Netherlands,0.5,0,0,Kirtipur,Tribhuvan University International Cricket Gro...
...,...,...,...,...,...,...,...,...
214645,1784,Pakistan,New Zealand,19.2,6,0,NaN,Dubai International Cricket Stadium
214646,1784,Pakistan,New Zealand,19.3,0,Sohail Tanvir,NaN,Dubai International Cricket Stadium
214647,1784,Pakistan,New Zealand,19.4,1,0,NaN,Dubai International Cricket Stadium
214648,1784,Pakistan,New Zealand,19.5,2,0,NaN,Dubai International Cricket Stadium
214649,1784,Pakistan,New Zealand,19.6,0,Mohammad Amir,NaN,Dubai International Cricket Stadium

In [120]:
pickle.dump(output,open('dataset_level1.pkl12','wb'))